DEV: LEAF-2140 - Adding Workflow Status to Inbox Request Lists
VHAINNOVATIONS/LEAF pull request #1306
Opened 2021-05-04 18:12 UTC by gsteinhoff

2021-05-04 18:15 UTC, pete-nerantzinis approved these changes

2021-05-04 19:09 UTC, Pelentan requested changes
I'm not seeing the "fail" catch for the ajax call.  

Please remember to include comments for all new functions.

2021-05-05 14:02 UTC, gsteinhoff commented
Converted all JS to own JS file with comments and fixed the Title AJAX request to have a fail status handler.

2021-05-05 14:37 UTC, Vaceek approved these changes

2021-05-06 18:09 UTC, Pelentan approved these changes
Looks good.

2021-05-06 18:09 UTC, merged