propagate change events
VHAINNOVATIONS/LEAF pull request #1448
Opened 2021-08-11 19:36 UTC by Pelentan

This is from Michael Gao

2021-08-11 19:42 UTC, AmandaSumner approved these changes

2021-08-11 19:42 UTC, maxrichardjr approved these changes
Looks good.

2021-08-12 12:47 UTC, gsteinhoff approved these changes

2021-08-12 15:17 UTC, pete-nerantzinis requested changes
I dont see the reason for this as there are no indicator ids that hold a change event besides multiselect. This woulnd't trigger on anything I think, I even went through the entire tpls I see nothing that has a change event.

2021-08-12 20:02 UTC, aerinkayne approved these changes

2021-08-13 20:18 UTC, merged

2021-08-17 20:56 UTC, mgaoVA commented
> I dont see the reason for this as there are no indicator ids that hold a change event besides multiselect. This woulnd't trigger on anything I think, I even went through the entire tpls I see nothing that has a change event.
> 
> I guess its more so me wanting to know what exactly is this triggering. @mgaoVA

@pete-nerantzinis Sorry missed your message here. This resolves a consistency issue for custom UI devs that rely on expected behavior of input fields. Standard input fields such as text/textarea/number automatically trigger changes on their respective field's ID #.

Since the underlying DOM object is not directly controlled by users for the orgchart_employee widget, change events would never fire as expected.