LEAF-2473 New Row logic update
VHAINNOVATIONS/LEAF pull request #1463
Opened 2021-09-07 18:55 UTC by aerinkayne

Addresses the situation of the New Row button not appearing if no rows are returned from the search.

2021-09-07 18:58 UTC, AmandaSumner approved these changes

2021-09-07 19:04 UTC, maxrichardjr approved these changes
Looks good

2021-09-08 12:24 UTC, raphaelfretter approved these changes
Looks good

2021-09-08 14:18 UTC, Pelentan requested changes

2021-09-08 14:18 UTC, Pelentan commented on LEAF_Request_Portal/templates/view_reports.tpl
> +function checkIfOneTypeSearchedAndUpdate(searchQueryTerms) {
Need some type checking on searchQueryTerms.  I know IE doesn't like it in the call, but inside the function we need to ensure it's actually and object so later calls don't fail badly.

2021-09-10 18:47 UTC, pete-nerantzinis approved these changes
Looks good

2021-09-16 16:19 UTC, Pelentan approved these changes

2021-09-16 16:42 UTC, beingforthebenefit approved these changes

2021-09-20 12:11 UTC, merged